"""The profile-scaling forms, fitted from a file pair and applied to a profile.

Single source for `nstx_scaling_check.ipynb` section 5 and for
`run_nstx_omtomn_scan.py --match-hatch`. The notebook cell is generated by
inlining this file, and the runner imports it, so a mimic run and the notebook's
measurement cannot disagree about what a scaling *is*: same fit, same winner,
same rebuild, same numbers.

Three candidate forms, because "scaled by 1.3" is ambiguous and the readings
differ by more than a factor:

    value x c     y_new = c * y
                  value ratio flat at c across every radius, core included

    ramped x c    y_new = y * (1 + (c-1) * w(rho))
                  value ratio 1 in the core, c at the edge

    power law     y_new = y_piv * (y/y_piv)**(1 + (alpha-1) * w(rho))
                  what apply_omt / apply_omne do: pivot held, gradient scaled

with the ramp

    w(rho) = (tanh((rho - topped)/(midped - topped)) + 1) / 2

A value multiply is INVISIBLE to a power-law fit -- normalising by the pivot
cancels the constant, the exponent comes back as exactly 1, and the
"reproduction" is the base profile. That is why all three are fitted and ranked
on the profile itself rather than one being assumed.
"""

from __future__ import annotations

import numpy as np

# The radii both consumers tabulate, so their tables line up row for row.
PROBE_RHO = (0.0, 0.3, 0.5, 0.7, 0.8, 0.9, 0.95, 0.99)

FORMS = ("value x c", "ramped x c", "power law")


def read_gene(path):
    """(rho_tor, T[keV], n[1e19 m^-3]) by column order, not header wording."""
    d = np.loadtxt(path, comments="#")
    return d[:, 0], d[:, 2], d[:, 3]


def ramp_weight(rhot, top, mid):
    return (np.tanh((rhot - top) / (mid - top)) + 1) / 2


def omega_of(rhot, y):
    """-d ln y / d rho, the normalised log-gradient the alphas are named for."""
    return -np.gradient(np.log(y), rhot)


def gradient_ratio(rhot, base, scaled, floor_frac=0.05):
    """omega_scaled/omega_base, NaN where omega_base is too small to divide by."""
    ob, os_ = omega_of(rhot, base), omega_of(rhot, scaled)
    floor = floor_frac * np.nanmax(np.abs(ob))
    return np.where(np.abs(ob) < floor, np.nan, os_ / ob)


def fit_forms(rhot, base, scaled):
    """{form: (params, rms)} for all three forms, rms relative and comparable."""
    from scipy.optimize import least_squares

    m = (rhot > 0.02) & (rhot < 0.98) & (base > 0) & (scaled > 0)
    x, yb, ys = rhot[m], base[m], scaled[m]

    def rel(pred):
        return float(np.sqrt(np.mean((pred / ys - 1) ** 2)))

    out = {}
    c = float(np.median(ys / yb))
    out["value x c"] = ((c,), rel(c * yb))

    def resid_ramped(p):
        return yb * (1 + (p[0] - 1) * ramp_weight(x, p[1], p[2])) / ys - 1

    best = None
    for c0 in (0.8, 1.3):
        for t0 in (0.0, 0.5, 0.8):
            r = least_squares(resid_ramped, [c0, t0, 1.0],
                              bounds=([0.1, -2.0, 0.5], [5.0, 0.95, 3.0]))
            if best is None or r.cost < best.cost:
                best = r
    out["ramped x c"] = (tuple(best.x),
                         rel(yb * (1 + (best.x[0] - 1)
                                   * ramp_weight(x, best.x[1], best.x[2]))))

    piv = base[-1]

    def resid_power(p):
        expo = 1 + (p[0] - 1) * ramp_weight(x, p[1], p[2])
        return piv * (yb / piv) ** expo / ys - 1

    best = None
    for a0 in (0.7, 1.3, 2.0):
        for t0 in (0.0, 0.3, 0.8):
            r = least_squares(resid_power, [a0, t0, 1.0],
                              bounds=([0.1, -2.0, 0.5], [5.0, 0.95, 3.0]))
            if best is None or r.cost < best.cost:
                best = r
    expo = 1 + (best.x[0] - 1) * ramp_weight(x, best.x[1], best.x[2])
    out["power law"] = (tuple(best.x), rel(piv * (yb / piv) ** expo))
    return out


def pick_form(rhot, base, scaled):
    """(form, params, rms, all_forms) -- the lowest-rms form for one pair."""
    forms = fit_forms(rhot, base, scaled)
    winner = min(forms, key=lambda k: forms[k][1])
    return (winner,) + forms[winner] + (forms,)


def rebuild(rhot, base, form, params):
    """Apply one form to a base profile. The inverse of pick_form."""
    if form == "value x c":
        return params[0] * base
    if form == "ramped x c":
        c, top, mid = params
        return base * (1 + (c - 1) * ramp_weight(rhot, top, mid))
    if form == "power law":
        alpha, top, mid = params
        piv = base[-1]
        return piv * (base / piv) ** (1 + (alpha - 1)
                                      * ramp_weight(rhot, top, mid))
    raise ValueError(f"unknown form {form!r}; expected one of {FORMS}")


def hatch_sets(d):
    """{suffix: {spec: path}} for one directory, or {} if it is not a run.

    A run holds the bare profiles_{e,i,z} plus at least one suffixed set; the
    bare set is the reference the scaled ones are measured against.
    """
    import glob
    import os

    out = {}
    for path in sorted(glob.glob(os.path.join(d, "profiles_e*"))):
        suffix = os.path.basename(path)[len("profiles_e"):]
        trio = {sp: os.path.join(d, f"profiles_{sp}{suffix}")
                for sp in ("e", "i", "z")}
        if all(os.path.isfile(p) for p in trio.values()):
            out[suffix] = trio
    return out if "" in out and len(out) > 1 else {}


def hatch_runs(root):
    """{run name: sets} for root itself, else for each of its subdirectories."""
    import os

    own = hatch_sets(root)
    if own:
        return {os.path.basename(os.path.normpath(root)): own}
    found = {}
    for entry in sorted(os.listdir(root)):
        d = os.path.join(root, entry)
        got = hatch_sets(d) if os.path.isdir(d) else {}
        if got:
            found[entry] = got
    return found


# Which dataset variable each (profiles file, column) pair carries.
COLUMNS = (("e", "Te", "ne"), ("i", "Ti", "ni"), ("z", "Tz", "nz"))


def measure_sets(sets, suffix):
    """{variable: (form, params, rms)} for one scaled set against the bare one.

    Every variable the files carry is measured on its own -- the T-only / n-only
    split then falls out of the measurement (an untouched variable fits
    `value x c` with c = 1) instead of being asserted by whoever wrote the flag.
    """
    measured = {}
    for spec, tname, nname in COLUMNS:
        if spec not in sets[""] or spec not in sets[suffix]:
            continue
        rhot, Tb, nb = read_gene(sets[""][spec])
        _, Ts, ns = read_gene(sets[suffix][spec])
        for var, base, scaled in ((tname, Tb, Ts), (nname, nb, ns)):
            form, params, rms, _ = pick_form(rhot, base, scaled)
            measured[var] = (form, params, rms)
    return measured
